// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";

Jest.describe("Placeholder", (function (param) {
        return Jest.test("Placeholder test", (function (param) {
                      return Jest.Expect[/* toEqual */12](true, Jest.Expect[/* expect */0](true));
                    }));
      }));

export {
  
}
/*  Not a pure module */
